In [4]:
import os
import django
import pandas as pd
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'fxfutbol.settings')
django.setup()
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

In [5]:
from analysis.models import MatchStats
fixture_data = MatchStats.objects.all().values()
df = pd.DataFrame(list(fixture_data))
df

,id,tarih,stats,update_date
0,11907427,2024-10-07,"{'match_id': 11907427, 'lineups': {'match_id':...",2024-10-09 22:07:48.850918+00:00
1,11907428,2024-10-07,"{'match_id': 11907428, 'lineups': {'match_id':...",2024-10-09 22:07:48.851376+00:00
2,11907429,2024-10-06,"{'match_id': 11907429, 'lineups': {'match_id':...",2024-10-09 21:56:06.245948+00:00
3,11907430,2024-10-07,"{'match_id': 11907430, 'lineups': {'match_id':...",2024-10-09 22:07:48.852800+00:00
4,11907432,2024-10-07,"{'match_id': 11907432, 'lineups': {'match_id':...",2024-10-09 22:07:48.851819+00:00
...,...,...,...,...
828,12944926,2024-10-09,"{'match_id': 12944926, 'lineups': {'match_id':...",2024-10-09 21:25:32.245487+00:00
829,12959814,2024-10-09,"{'match_id': 12959814, 'lineups': {'match_id':...",2024-10-09 21:25:32.245929+00:00
830,12962059,2024-10-09,"{'match_id': 12962059, 'lineups': {'match_id':...",2024-10-09 21:25:32.245663+00:00
831,12962060,2024-10-09,"{'match_id': 12962060, 'lineups': {'match_id':...",2024-10-09 21:25:32.245840+00:00
832,12962061,2024-10-09,"{'match_id': 12962061, 'lineups': {'match_id':...",2024-10-09 21:25:32.245882+00:00

In [6]:
df["stats"][0].keys()

dict_keys(['match_id', 'lineups', 'incidents', 'graph', 'match_info', 'odds', 'pregame_form', 'statistics'])

In [7]:
stats_df = pd.json_normalize(df['stats'])

stats_df

,match_id,lineups.match_id,lineups.response_code,lineups.data.confirmed,lineups.data.home.players,lineups.data.home.supportStaff,lineups.data.home.formation,lineups.data.home.playerColor.primary,lineups.data.home.playerColor.number,lineups.data.home.playerColor.outline,...,match_info.data.event.awayScore.penalties,match_info.data.event.awayTeam.createdByEditor,match_info.data.event.tournament.roundPrefix,match_info.data.event.homeScore.extra1,match_info.data.event.homeScore.extra2,match_info.data.event.awayScore.extra1,match_info.data.event.awayScore.extra2,match_info.data.event.time.extra1StartTimestamp,match_info.data.event.time.extra2StartTimestamp,match_info.data.event.aggregatedWinnerCode
0,11907427,11907427,200,True,"[{'player': {'name': 'Kristoffer Nordfeldt', '...",[],5-4-1,000000,ffff00,000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11907428,11907428,200,True,"[{'player': {'name': 'Oscar Jansson', 'slug': ...",[],4-2-3-1,132845,5ed9ff,132845,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11907429,11907429,200,True,"[{'player': {'name': 'Warner Hahn', 'firstName...",[],4-2-3-1,ffffff,008000,ffffff,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11907430,11907430,200,True,"[{'player': {'name': 'Ricardo Friedrich', 'slu...",[],4-4-2,79bcff,ffffff,79bcff,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11907432,11907432,200,True,"[{'player': {'name': 'David Mitov Nilsson', 's...",[],4-2-3-1,fcfcfd,0000ff,fcfcfd,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,12944926,12944926,200,True,"[{'player': {'name': 'Connor Roberts', 'slug':...",[],4-3-3,ffffff,dd0000,ffffff,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
829,12959814,12959814,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,12962059,12962059,200,True,"[{'player': {'name': 'Rafael Munteanu', 'first...",[],4-3-3,ff0000,ffff00,ff0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
831,12962060,12962060,200,True,"[{'player': {'name': 'Konstantin Heide', 'firs...",[],4-3-3,ffffff,000000,ffffff,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,12962061,12962061,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
columns = list(stats_df.columns)
columns

['match_id',
 'lineups.match_id',
 'lineups.response_code',
 'lineups.data.confirmed',
 'lineups.data.home.players',
 'lineups.data.home.supportStaff',
 'lineups.data.home.formation',
 'lineups.data.home.playerColor.primary',
 'lineups.data.home.playerColor.number',
 'lineups.data.home.playerColor.outline',
 'lineups.data.home.playerColor.fancyNumber',
 'lineups.data.home.goalkeeperColor.primary',
 'lineups.data.home.goalkeeperColor.number',
 'lineups.data.home.goalkeeperColor.outline',
 'lineups.data.home.goalkeeperColor.fancyNumber',
 'lineups.data.away.players',
 'lineups.data.away.supportStaff',
 'lineups.data.away.formation',
 'lineups.data.away.playerColor.primary',
 'lineups.data.away.playerColor.number',
 'lineups.data.away.playerColor.outline',
 'lineups.data.away.playerColor.fancyNumber',
 'lineups.data.away.goalkeeperColor.primary',
 'lineups.data.away.goalkeeperColor.number',
 'lineups.data.away.goalkeeperColor.outline',
 'lineups.data.away.goalkeeperColor.fancyNumber',
 'incidents.match_id',
 'incidents.response_code',
 'incidents.data.incidents',
 'incidents.data.home.goalkeeperColor.primary',
 'incidents.data.home.goalkeeperColor.number',
 'incidents.data.home.goalkeeperColor.outline',
 'incidents.data.home.goalkeeperColor.fancyNumber',
 'incidents.data.home.playerColor.primary',
 'incidents.data.home.playerColor.number',
 'incidents.data.home.playerColor.outline',
 'incidents.data.home.playerColor.fancyNumber',
 'incidents.data.away.goalkeeperColor.primary',
 'incidents.data.away.goalkeeperColor.number',
 'incidents.data.away.goalkeeperColor.outline',
 'incidents.data.away.goalkeeperColor.fancyNumber',
 'incidents.data.away.playerColor.primary',
 'incidents.data.away.playerColor.number',
 'incidents.data.away.playerColor.outline',
 'incidents.data.away.playerColor.fancyNumber',
 'graph.match_id',
 'graph.response_code',
 'graph.data.graphPoints',
 'graph.data.periodTime',
 'graph.data.periodCount',
 'match_info.match_id',
 'match_info.response_code',
 'match_info.data.event.tournament.name',
 'match_info.data.event.tournament.slug',
 'match_info.data.event.tournament.category.name',
 'match_info.data.event.tournament.category.slug',
 'match_info.data.event.tournament.category.sport.name',
 'match_info.data.event.tournament.category.sport.slug',
 'match_info.data.event.tournament.category.sport.id',
 'match_info.data.event.tournament.category.id',
 'match_info.data.event.tournament.category.country.alpha2',
 'match_info.data.event.tournament.category.country.alpha3',
 'match_info.data.event.tournament.category.country.name',
 'match_info.data.event.tournament.category.country.slug',
 'match_info.data.event.tournament.category.flag',
 'match_info.data.event.tournament.category.alpha2',
 'match_info.data.event.tournament.uniqueTournament.name',
 'match_info.data.event.tournament.uniqueTournament.slug',
 'match_info.data.event.tournament.uniqueTournament.primaryColorHex',
 'match_info.data.event.tournament.uniqueTournament.secondaryColorHex',
 'match_info.data.event.tournament.uniqueTournament.category.name',
 'match_info.data.event.tournament.uniqueTournament.category.slug',
 'match_info.data.event.tournament.uniqueTournament.category.sport.name',
 'match_info.data.event.tournament.uniqueTournament.category.sport.slug',
 'match_info.data.event.tournament.uniqueTournament.category.sport.id',
 'match_info.data.event.tournament.uniqueTournament.category.id',
 'match_info.data.event.tournament.uniqueTournament.category.country.alpha2',
 'match_info.data.event.tournament.uniqueTournament.category.country.alpha3',
 'match_info.data.event.tournament.uniqueTournament.category.country.name',
 'match_info.data.event.tournament.uniqueTournament.category.country.slug',
 'match_info.data.event.tournament.uniqueTournament.category.flag',
 'match_info.data.event.tournament.uniqueTournament.category.alpha2',
 'match_info.data.event.tournament.uniqueTournament.userCount',
 'match_info.data.event.tournament.uniqueTournament.id',
 'match_info.data.event.tournament.uniqueTournament.hasPerformanceGraphFeature',
 'match_info.data.event.tournament.uniqueTournament.hasEventPlayerStatistics',
 'match_info.data.event.tournament.uniqueTournament.displayInverseHomeAwayTeams',
 'match_info.data.event.tournament.priority',
 'match_info.data.event.tournament.isGroup',
 'match_info.data.event.tournament.competitionType',
 'match_info.data.event.tournament.isLive',
 'match_info.data.event.tournament.id',
 'match_info.data.event.season.name',
 'match_info.data.event.season.year',
 'match_info.data.event.season.editor',
 'match_info.data.event.season.id',
 'match_info.data.event.roundInfo.round',
 'match_info.data.event.customId',
 'match_info.data.event.status.code',
 'match_info.data.event.status.description',
 'match_info.data.event.status.type',
 'match_info.data.event.winnerCode',
 'match_info.data.event.venue.city.name',
 'match_info.data.event.venue.venueCoordinates.latitude',
 'match_info.data.event.venue.venueCoordinates.longitude',
 'match_info.data.event.venue.hidden',
 'match_info.data.event.venue.slug',
 'match_info.data.event.venue.name',
 'match_info.data.event.venue.capacity',
 'match_info.data.event.venue.id',
 'match_info.data.event.venue.country.alpha2',
 'match_info.data.event.venue.country.alpha3',
 'match_info.data.event.venue.country.name',
 'match_info.data.event.venue.country.slug',
 'match_info.data.event.venue.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.venue.stadium.name',
 'match_info.data.event.venue.stadium.capacity',
 'match_info.data.event.referee.name',
 'match_info.data.event.referee.slug',
 'match_info.data.event.referee.yellowCards',
 'match_info.data.event.referee.redCards',
 'match_info.data.event.referee.yellowRedCards',
 'match_info.data.event.referee.games',
 'match_info.data.event.referee.sport.id',
 'match_info.data.event.referee.sport.slug',
 'match_info.data.event.referee.sport.name',
 'match_info.data.event.referee.id',
 'match_info.data.event.referee.country.alpha2',
 'match_info.data.event.referee.country.alpha3',
 'match_info.data.event.referee.country.name',
 'match_info.data.event.referee.country.slug',
 'match_info.data.event.homeTeam.name',
 'match_info.data.event.homeTeam.slug',
 'match_info.data.event.homeTeam.shortName',
 'match_info.data.event.homeTeam.gender',
 'match_info.data.event.homeTeam.sport.name',
 'match_info.data.event.homeTeam.sport.slug',
 'match_info.data.event.homeTeam.sport.id',
 'match_info.data.event.homeTeam.userCount',
 'match_info.data.event.homeTeam.manager.name',
 'match_info.data.event.homeTeam.manager.slug',
 'match_info.data.event.homeTeam.manager.shortName',
 'match_info.data.event.homeTeam.manager.id',
 'match_info.data.event.homeTeam.manager.country.alpha2',
 'match_info.data.event.homeTeam.manager.country.alpha3',
 'match_info.data.event.homeTeam.manager.country.name',
 'match_info.data.event.homeTeam.manager.country.slug',
 'match_info.data.event.homeTeam.manager.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.homeTeam.manager.fieldTranslations.shortNameTranslation.ar',
 'match_info.data.event.homeTeam.venue.city.name',
 'match_info.data.event.homeTeam.venue.venueCoordinates.latitude',
 'match_info.data.event.homeTeam.venue.venueCoordinates.longitude',
 'match_info.data.event.homeTeam.venue.hidden',
 'match_info.data.event.homeTeam.venue.slug',
 'match_info.data.event.homeTeam.venue.name',
 'match_info.data.event.homeTeam.venue.capacity',
 'match_info.data.event.homeTeam.venue.id',
 'match_info.data.event.homeTeam.venue.country.alpha2',
 'match_info.data.event.homeTeam.venue.country.alpha3',
 'match_info.data.event.homeTeam.venue.country.name',
 'match_info.data.event.homeTeam.venue.country.slug',
 'match_info.data.event.homeTeam.venue.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.homeTeam.venue.stadium.name',
 'match_info.data.event.homeTeam.venue.stadium.capacity',
 'match_info.data.event.homeTeam.nameCode',
 'match_info.data.event.homeTeam.class',
 'match_info.data.event.homeTeam.disabled',
 'match_info.data.event.homeTeam.national',
 'match_info.data.event.homeTeam.type',
 'match_info.data.event.homeTeam.id',
 'match_info.data.event.homeTeam.country.alpha2',
 'match_info.data.event.homeTeam.country.alpha3',
 'match_info.data.event.homeTeam.country.name',
 'match_info.data.event.homeTeam.country.slug',
 'match_info.data.event.homeTeam.subTeams',
 'match_info.data.event.homeTeam.fullName',
 'match_info.data.event.homeTeam.teamColors.primary',
 'match_info.data.event.homeTeam.teamColors.secondary',
 'match_info.data.event.homeTeam.teamColors.text',
 'match_info.data.event.homeTeam.foundationDateTimestamp',
 'match_info.data.event.homeTeam.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.homeTeam.fieldTranslations.nameTranslation.ru',
 'match_info.data.event.awayTeam.name',
 'match_info.data.event.awayTeam.slug',
 'match_info.data.event.awayTeam.shortName',
 'match_info.data.event.awayTeam.gender',
 'match_info.data.event.awayTeam.sport.name',
 'match_info.data.event.awayTeam.sport.slug',
 'match_info.data.event.awayTeam.sport.id',
 'match_info.data.event.awayTeam.userCount',
 'match_info.data.event.awayTeam.manager.name',
 'match_info.data.event.awayTeam.manager.slug',
 'match_info.data.event.awayTeam.manager.shortName',
 'match_info.data.event.awayTeam.manager.id',
 'match_info.data.event.awayTeam.manager.country.alpha2',
 'match_info.data.event.awayTeam.manager.country.alpha3',
 'match_info.data.event.awayTeam.manager.country.name',
 'match_info.data.event.awayTeam.manager.country.slug',
 'match_info.data.event.awayTeam.venue.city.name',
 'match_info.data.event.awayTeam.venue.venueCoordinates.latitude',
 'match_info.data.event.awayTeam.venue.venueCoordinates.longitude',
 'match_info.data.event.awayTeam.venue.hidden',
 'match_info.data.event.awayTeam.venue.slug',
 'match_info.data.event.awayTeam.venue.name',
 'match_info.data.event.awayTeam.venue.capacity',
 'match_info.data.event.awayTeam.venue.id',
 'match_info.data.event.awayTeam.venue.country.alpha2',
 'match_info.data.event.awayTeam.venue.country.alpha3',
 'match_info.data.event.awayTeam.venue.country.name',
 'match_info.data.event.awayTeam.venue.country.slug',
 'match_info.data.event.awayTeam.venue.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.awayTeam.venue.stadium.name',
 'match_info.data.event.awayTeam.venue.stadium.capacity',
 'match_info.data.event.awayTeam.nameCode',
 'match_info.data.event.awayTeam.class',
 'match_info.data.event.awayTeam.disabled',
 'match_info.data.event.awayTeam.national',
 'match_info.data.event.awayTeam.type',
 'match_info.data.event.awayTeam.id',
 'match_info.data.event.awayTeam.country.alpha2',
 'match_info.data.event.awayTeam.country.alpha3',
 'match_info.data.event.awayTeam.country.name',
 'match_info.data.event.awayTeam.country.slug',
 'match_info.data.event.awayTeam.subTeams',
 'match_info.data.event.awayTeam.fullName',
 'match_info.data.event.awayTeam.teamColors.primary',
 'match_info.data.event.awayTeam.teamColors.secondary',
 'match_info.data.event.awayTeam.teamColors.text',
 'match_info.data.event.awayTeam.foundationDateTimestamp',
 'match_info.data.event.awayTeam.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.awayTeam.fieldTranslations.nameTranslation.ru',
 'match_info.data.event.homeScore.current',
 'match_info.data.event.homeScore.display',
 'match_info.data.event.homeScore.period1',
 'match_info.data.event.homeScore.period2',
 'match_info.data.event.homeScore.normaltime',
 'match_info.data.event.awayScore.current',
 'match_info.data.event.awayScore.display',
 'match_info.data.event.awayScore.period1',
 'match_info.data.event.awayScore.period2',
 'match_info.data.event.awayScore.normaltime',
 'match_info.data.event.time.injuryTime1',
 'match_info.data.event.time.injuryTime2',
 'match_info.data.event.time.currentPeriodStartTimestamp',
 'match_info.data.event.changes.changes',
 'match_info.data.event.changes.changeTimestamp',
 'match_info.data.event.hasGlobalHighlights',
 'match_info.data.event.hasEventPlayerStatistics',
 'match_info.data.event.hasEventPlayerHeatMap',
 'match_info.data.event.detailId',
 'match_info.data.event.crowdsourcingDataDisplayEnabled',
 'match_info.data.event.id',
 'match_info.data.event.defaultPeriodCount',
 'match_info.data.event.defaultPeriodLength',
 'match_info.data.event.defaultOvertimeLength',
 'match_info.data.event.currentPeriodStartTimestamp',
 'match_info.data.event.startTimestamp',
 'match_info.data.event.slug',
 'match_info.data.event.finalResultOnly',
 'match_info.data.event.feedLocked',
 'match_info.data.event.fanRatingEvent',
 'match_info.data.event.seasonStatisticsType',
 'match_info.data.event.showTotoPromo',
 'match_info.data.event.isEditor',
 'odds.match_id',
 'odds.response_code',
 'odds.data.featured.default.structureType',
 'odds.data.featured.default.marketId',
 'odds.data.featured.default.marketName',
 'odds.data.featured.default.isLive',
 'odds.data.featured.default.suspended',
 'odds.data.featured.default.id',
 'odds.data.featured.default.choices',
 'odds.data.featured.asian.structureType',
 'odds.data.featured.asian.marketId',
 'odds.data.featured.asian.marketName',
 'odds.data.featured.asian.isLive',
 'odds.data.featured.asian.suspended',
 'odds.data.featured.asian.id',
 'odds.data.featured.asian.choices',
 'odds.data.featured.fullTime.structureType',
 'odds.data.featured.fullTime.marketId',
 'odds.data.featured.fullTime.marketName',
 'odds.data.featured.fullTime.isLive',
 'odds.data.featured.fullTime.suspended',
 'odds.data.featured.fullTime.id',
 'odds.data.featured.fullTime.choices',
 'odds.data.hasMoreOdds',
 'pregame_form.match_id',
 'pregame_form.response_code',
 'pregame_form.data.homeTeam.avgRating',
 'pregame_form.data.homeTeam.position',
 'pregame_form.data.homeTeam.value',
 'pregame_form.data.homeTeam.form',
 'pregame_form.data.awayTeam.avgRating',
 'pregame_form.data.awayTeam.position',
 'pregame_form.data.awayTeam.value',
 'pregame_form.data.awayTeam.form',
 'pregame_form.data.label',
 'statistics.match_id',
 'statistics.response_code',
 'statistics.data.statistics',
 'match_info.data.event.hasBet365LiveStream',
 'match_info.data.event.bet365ExcludedCountryCodes',
 'match_info.data.event.attendance',
 'match_info.data.event.awayTeam.manager.fieldTranslations.nameTranslation.ar',
 'match_info.data.event.awayTeam.manager.fieldTranslations.shortNameTranslation.ar',
 'match_info.data.event.time.period1StartTimestamp',
 'match_info.data.event.time.period2StartTimestamp',
 'match_info.data.event.hasXg',
 'odds.data.error.code',
 'odds.data.error.message',
 'match_info.data.event.awayRedCards',
 'graph.data.error.code',
 'graph.data.error.message',
 'match_info.data.event.homeRedCards',
 'statistics.data.error.code',
 'statistics.data.error.message',
 'match_info.data.event.streamContentId',
 'lineups.data.error.code',
 'lineups.data.error.message',
 'lineups.data.home.missingPlayers',
 'lineups.data.away.missingPlayers',
 'match_info.data.event.season.seasonCoverageInfo.editorCoverageLevel',
 'match_info.data.event.roundInfo.name',
 'match_info.data.event.roundInfo.slug',
 'match_info.data.event.roundInfo.cupRoundType',
 'match_info.data.event.cupMatchesInRound',
 'pregame_form.data.error.code',
 'pregame_form.data.error.message',
 'match_info.data.event.homeScore.overtime',
 'match_info.data.event.awayScore.overtime',
 'match_info.data.event.time.injuryTime3',
 'match_info.data.event.time.injuryTime4',
 'match_info.data.event.homeTeam.createdByEditor',
 'match_info.data.event.tournament.groupName',
 'match_info.data.event.homeScore.penalties',
 'match_info.data.event.awayScore.penalties',
 'match_info.data.event.awayTeam.createdByEditor',
 'match_info.data.event.tournament.roundPrefix',
 'match_info.data.event.homeScore.extra1',
 'match_info.data.event.homeScore.extra2',
 'match_info.data.event.awayScore.extra1',
 'match_info.data.event.awayScore.extra2',
 'match_info.data.event.time.extra1StartTimestamp',
 'match_info.data.event.time.extra2StartTimestamp',
 'match_info.data.event.aggregatedWinnerCode']

In [9]:
match_columns = [col for col in columns if col.startswith("line")]
match_columns

['lineups.match_id',
 'lineups.response_code',
 'lineups.data.confirmed',
 'lineups.data.home.players',
 'lineups.data.home.supportStaff',
 'lineups.data.home.formation',
 'lineups.data.home.playerColor.primary',
 'lineups.data.home.playerColor.number',
 'lineups.data.home.playerColor.outline',
 'lineups.data.home.playerColor.fancyNumber',
 'lineups.data.home.goalkeeperColor.primary',
 'lineups.data.home.goalkeeperColor.number',
 'lineups.data.home.goalkeeperColor.outline',
 'lineups.data.home.goalkeeperColor.fancyNumber',
 'lineups.data.away.players',
 'lineups.data.away.supportStaff',
 'lineups.data.away.formation',
 'lineups.data.away.playerColor.primary',
 'lineups.data.away.playerColor.number',
 'lineups.data.away.playerColor.outline',
 'lineups.data.away.playerColor.fancyNumber',
 'lineups.data.away.goalkeeperColor.primary',
 'lineups.data.away.goalkeeperColor.number',
 'lineups.data.away.goalkeeperColor.outline',
 'lineups.data.away.goalkeeperColor.fancyNumber',
 'lineups.data.error.code',
 'lineups.data.error.message',
 'lineups.data.home.missingPlayers',
 'lineups.data.away.missingPlayers']

In [24]:
mycols = ["lineups.match_id","lineups.response_code",
          "match_info.data.event.homeTeam.id","match_info.data.event.awayTeam.id",
          "match_info.data.event.homeTeam.name","match_info.data.event.awayTeam.name",
          "lineups.data.home.players","lineups.data.away.players",
          "lineups.data.home.missingPlayers","lineups.data.away.missingPlayers"]

data = stats_df[mycols]
data.columns = ["match_id","code_response",
                "home_id","away_id",
                "home_name","away_name",
                "home_players","away_players",
                "home_missing","away_missing"]
data

,match_id,code_response,home_id,away_id,home_name,away_name,home_players,away_players,home_missing,away_missing
0,11907427,200,1764,1760,AIK,BK HÃ¤cken,"[{'player': {'name': 'Kristoffer Nordfeldt', '...","[{'player': {'name': 'Peter Abrahamsson', 'slu...",NaN,NaN
1,11907428,200,1759,1891,DjurgÃ¥rdens IF,Kalmar FF,"[{'player': {'name': 'Oscar Jansson', 'slug': ...","[{'player': {'name': 'Samuel Brolin', 'firstNa...",NaN,NaN
2,11907429,200,1758,1767,Hammarby IF,Halmstads BK,"[{'player': {'name': 'Warner Hahn', 'firstName...","[{'player': {'name': 'Tim RÃ¶nning', 'slug': 't...",NaN,NaN
3,11907430,200,1892,1842,MalmÃ¶ FF,IFK VÃ¤rnamo,"[{'player': {'name': 'Ricardo Friedrich', 'slu...","[{'player': {'name': 'Viktor Andersson', 'firs...",NaN,NaN
4,11907432,200,1769,1761,IFK NorrkÃ¶ping,IFK GÃ¶teborg,"[{'player': {'name': 'David Mitov Nilsson', 's...","[{'player': {'name': 'Jacob KarlstrÃ¸m', 'slug'...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
828,12944926,200,4921,4909,The New Saints,Caernarfon Town,"[{'player': {'name': 'Connor Roberts', 'slug':...","[{'player': {'name': 'Hari Thomas', 'slug': 'h...",NaN,NaN
829,12959814,404,22551,22513,Ireland U19,Greece U19,NaN,NaN,NaN,NaN
830,12962059,200,22552,22545,Romania U19,Norway U19,"[{'player': {'name': 'Rafael Munteanu', 'first...","[{'player': {'name': 'Magnus Jensen', 'slug': ...",NaN,NaN
831,12962060,200,22512,22560,Germany U19,Spain U19,"[{'player': {'name': 'Konstantin Heide', 'firs...","[{'player': {'name': 'RaÃºl JimÃ©nez Latorre', '...",NaN,NaN
832,12962061,404,22509,22502,France U19,Denmark U19,NaN,NaN,NaN,NaN

In [45]:
datax = pd.json_normalize(data['home_players'])
datax["match_id"]=data["match_id"]
datax

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,match_id
0,"{'shirtNumber': 15, 'jerseyNumber': '15', 'pos...","{'shirtNumber': 2, 'jerseyNumber': '2', 'posit...","{'shirtNumber': 5, 'jerseyNumber': '5', 'posit...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 16, 'jerseyNumber': '16', 'pos...","{'shirtNumber': 12, 'jerseyNumber': '12', 'pos...","{'shirtNumber': 8, 'jerseyNumber': '8', 'posit...","{'shirtNumber': 19, 'jerseyNumber': '19', 'pos...","{'shirtNumber': 7, 'jerseyNumber': '7', 'posit...","{'shirtNumber': 10, 'jerseyNumber': '10', 'pos...",...,"{'shirtNumber': 37, 'jerseyNumber': '37', 'pos...","{'shirtNumber': 21, 'jerseyNumber': '21', 'pos...",None,None,None,None,None,None,None,11907427
1,"{'shirtNumber': 45, 'jerseyNumber': '45', 'pos...","{'shirtNumber': 18, 'jerseyNumber': '18', 'pos...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 3, 'jerseyNumber': '3', 'posit...","{'shirtNumber': 27, 'jerseyNumber': '27', 'pos...","{'shirtNumber': 14, 'jerseyNumber': '14', 'pos...","{'shirtNumber': 6, 'jerseyNumber': '6', 'posit...","{'shirtNumber': 29, 'jerseyNumber': '29', 'pos...","{'shirtNumber': 20, 'jerseyNumber': '20', 'pos...","{'shirtNumber': 23, 'jerseyNumber': '23', 'pos...",...,"{'shirtNumber': 9, 'jerseyNumber': '9', 'posit...","{'shirtNumber': 13, 'jerseyNumber': '13', 'pos...","{'shirtNumber': 15, 'jerseyNumber': '15', 'pos...",None,None,None,None,None,None,11907428
2,"{'shirtNumber': 1, 'jerseyNumber': '1', 'posit...","{'shirtNumber': 22, 'jerseyNumber': '22', 'pos...","{'shirtNumber': 17, 'jerseyNumber': '17', 'pos...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 30, 'jerseyNumber': '30', 'pos...","{'shirtNumber': 11, 'jerseyNumber': '11', 'pos...","{'shirtNumber': 5, 'jerseyNumber': '5', 'posit...","{'shirtNumber': 18, 'jerseyNumber': '18', 'pos...","{'shirtNumber': 20, 'jerseyNumber': '20', 'pos...","{'shirtNumber': 28, 'jerseyNumber': '28', 'pos...",...,"{'shirtNumber': 31, 'jerseyNumber': '31', 'pos...","{'shirtNumber': 29, 'jerseyNumber': '29', 'pos...","{'shirtNumber': 19, 'jerseyNumber': '19', 'pos...",None,None,None,None,None,None,11907429
3,"{'shirtNumber': 1, 'jerseyNumber': '1', 'posit...","{'shirtNumber': 17, 'jerseyNumber': '17', 'pos...","{'shirtNumber': 18, 'jerseyNumber': '18', 'pos...","{'shirtNumber': 35, 'jerseyNumber': '35', 'pos...","{'shirtNumber': 25, 'jerseyNumber': '25', 'pos...","{'shirtNumber': 5, 'jerseyNumber': '5', 'posit...","{'shirtNumber': 23, 'jerseyNumber': '23', 'pos...","{'shirtNumber': 10, 'jerseyNumber': '10', 'pos...","{'shirtNumber': 7, 'jerseyNumber': '7', 'posit...","{'shirtNumber': 20, 'jerseyNumber': '20', 'pos...",...,"{'shirtNumber': 37, 'jerseyNumber': '37', 'pos...","{'shirtNumber': 33, 'jerseyNumber': '33', 'pos...","{'shirtNumber': 40, 'jerseyNumber': '40', 'pos...",None,None,None,None,None,None,11907430
4,"{'shirtNumber': 91, 'jerseyNumber': '91', 'pos...","{'shirtNumber': 24, 'jerseyNumber': '24', 'pos...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 19, 'jerseyNumber': '19', 'pos...","{'shirtNumber': 37, 'jerseyNumber': '37', 'pos...","{'shirtNumber': 21, 'jerseyNumber': '21', 'pos...","{'shirtNumber': 9, 'jerseyNumber': '9', 'posit...","{'shirtNumber': 15, 'jerseyNumber': '15', 'pos...","{'shirtNumber': 26, 'jerseyNumber': '26', 'pos...","{'shirtNumber': 8, 'jerseyNumber': '8', 'posit...",...,"{'shirtNumber': 16, 'jerseyNumber': '16', 'pos...","{'shirtNumber': 28, 'jerseyNumber': '28', 'pos...","{'shirtNumber': 35, 'jerseyNumber': '35', 'pos...",None,None,None,None,None,None,11907432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,"{'shirtNumber': 25, 'jerseyNumber': '25', 'pos...","{'shirtNumber': 7, 'jerseyNumber': '7', 'posit...","{'shirtNumber': 6, 'jerseyNumber': '6', 'posit...","{'shirtNumber': 22, 'jerseyNumber': '22', 'pos...","{'shirtNumber': 3, 'jerseyNumber': '3', 'posit...","{'shirtNumber': 21, 'jerseyNumber': '21', 'pos...","{'shirtNumber': 10, 'jerseyNumber': '10', 'pos...","{'shirtNumber': 19, 'jerseyNumber': '19', 'pos...","{'shirtNumber': 17, 'jerseyNumber': '17', 'pos...","{'shirtNumber': 9, 'jerseyNumber': '9', 'posit...",...,"{'shirtNumber': 33, 'jerseyNumber': '33', 'pos...",None,None,None,None,None,None,None,None,12944926
829,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,12959814
830,"{'shirtNumber': 12, 'jerseyNumber': '12', 'pos...","{'shirtNumber': 2, 'jerseyNumber': '2', 'posit...","{'shirtNumber': 3, 'jerseyNumber': '3', 'posit...","{'shirtNumber': 5, 'jerseyNumber': '5', 'posit...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 13, 'jerseyNumber': '13', 'pos...","{'shirtNumber': 8, 'jerseyNumber': '8', 'posit...","{'shirtNumber': 10, 'jerseyNumber': '10', 'pos...","{'shirtNumber': 11, 'jerseyNumber': '11', 'pos...","{'shirtNumber': 19, 'jerseyNumber': '19', 'pos...",...,"{'shirtNumber': 6, 'jerseyNumber': '6', 'posit...","{'shirtNumber': 15, 'jerseyNumber': '15', 'pos...","{'shirtNumber': 12, 'jerseyNumber': '12', 'pos...","{'shirtNumber': 23, 'jerseyNumber': '23', 'pos...","{'shirtNumber': 16, 'jerseyNumber': '16', 'pos...","{'shirtNumber': 20, 'jerseyNumber': '20', 'pos...",None,None,None,12962059
831,"{'shirtNumber': 1, 'jerseyNumber': '1', 'posit...","{'shirtNumber': 2, 'jerseyNumber': '2', 'posit...","{'shirtNumber': 5, 'jerseyNumber': '5', 'posit...","{'shirtNumber': 6, 'jerseyNumber': '6', 'posit...","{'shirtNumber': 3, 'jerseyNumber': '3', 'posit...","{'shirtNumber': 10, 'jerseyNumber': '10', 'pos...","{'shirtNumber': 4, 'jerseyNumber': '4', 'posit...","{'shirtNumber': 8, 'jerseyNumber': '8', 'posit...","{'shirtNumber': 11, 'jerseyNumber': '11', 'pos...","{'shirtNumber': 9, 'jerseyNumber': '9', 'posit...",...,"{'shirtNumber': 12, 'jerseyNumber': '12', 'pos...","{'shirtNumber': 14, 'jerseyNumber': '14', 'pos...","{'shirtNumber': 15, 'jerseyNumber': '15', 'pos...","{'shirtNumber': 13, 'jerseyNumber': '13', 'pos...",None,None,None,None,None,12962060
832,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,12962061

In [59]:
import numpy as np
match_ids = datax['match_id'].repeat(datax.iloc[:, :-1].apply(len, axis=)).reset_index(drop=True)

# TÃ¼m sÃ¼tunlardaki dict yapÄ±sÄ±nÄ± aÃ§mak ve uzun formata getirmek iÃ§in json_normalize kullanma
normalized_dfs = [pd.json_normalize(datax[col]) for col in datax.columns if col != 'match_id']

# TÃ¼m normalleÅŸtirilmiÅŸ DataFrame'leri birleÅŸtirme
result_df = pd.concat(normalized_dfs, ignore_index=True)

# `match_id` deÄŸerini normalleÅŸtirilmiÅŸ veriye ekleme
result_df['match_id'] = match_ids

# Sonucu gÃ¶sterme
result_df = result_df.fillna(0)
result_df = result_df[result_df["player.position"]!=0]
result_df

ValueError: operands could not be broadcast together with shape (833,) (26,)

In [58]:
result_df.to_excel("PlayerDataHome.xlsx")